[package]
name = "quanweb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.18", features = ["tracing", "json", "tower-log", "macros", "tokio", "headers", "query"] }
axum-extra = { version = "0.7.4", features = ["erased-json", "query", "typed-routing"] }
chrono = { version = "0.4.26", features = ["serde"] }
edgedb-derive = "0.5.0"
edgedb-errors = { version = "0.4.0", features = ["miette"] }
edgedb-protocol = { version = "0.6.0", features = ["all-types"] }
edgedb-tokio = { version = "0.5.0", features = ["serde_json", "miette-errors"] }
miette = { version = "5.9.0", features = ["fancy", "serde"] }
serde = { version = "1.0.164", features = ["serde_derive"] }
serde_with = { version = "3.0.0", features = ["chrono"] }
tokio = { version = "1.28.2", features = ["full"] }
tower-http = { version = "0.4.1", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
uuid = { version = "1.3.4", features = ["v1", "serde"] }
