[package]
name = "quanweb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.18", features = ["tracing"] }
axum-extra = { version = "0.7.4", features = ["erased-json"] }
edgedb-derive = "0.5.0"
edgedb-tokio = "0.4.0"
serde = { version = "1.0.164", features = ["serde_derive"] }
tokio = { version = "1.28.2", features = ["full"] }
tower-http = { version = "0.4.1", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
