[package]
name = "quanweb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-fred-session = "0.1.4"
async-trait = "0.1.68"
axum = { version = "0.6.18", features = ["tracing", "json", "tower-log", "macros", "tokio", "headers", "query", "original-uri"] }
axum-extra = { version = "0.7.4", features = ["erased-json", "query", "typed-routing"] }
axum-login = "0.5.0"
axum-sessions = "0.5.0"
axum-template = { version = "0.19.0", features = ["minijinja"] }
axum_garde = { version = "0.11.2", features = ["axum-extra", "axum-extra-query"] }
chrono = { version = "0.4.26", features = ["serde", "alloc", "clock"], default-features = false }
chrono-tz = { version = "0.8.3", features = ["serde"] }
comrak = "0.18.0"
config = { version = "0.13.3", default-features = false, features = ["indexmap", "toml"] }
djangohashers = { version = "1.6.7", default-features = false, features = ["with_argon2"] }
edgedb-derive = "0.5.1"
edgedb-errors = { version = "0.4.1", features = ["miette"] }
edgedb-protocol = { version = "0.6.0", features = ["all-types"] }
edgedb-tokio = { version = "0.5.0", features = ["serde_json", "miette-errors"] }
eyre = "0.6.8"
fred = { version = "6.3.0", features = ["serde-json", "partial-tracing"] }
garde = "0.11.2"
http = "0.2.9"
indexmap = { version = "2.0.0", features = ["serde"] }
libpassgen = "1.0.3"
miette = { version = "5.9.0", features = ["fancy", "serde"] }
mime_guess = "2.0.4"
minijinja = { version = "1.0.3", features = ["loader", "internal_debug"] }
minijinja-autoreload = "1.0.3"
querystring_tiny = "0.2.1"
redact = { version = "0.1.1", features = ["serde"] }
rust-embed = { version = "6.8.1", features = ["axum", "mime-guess", "include-exclude"] }
serde = { version = "1.0.164", features = ["serde_derive"] }
serde-value = "0.7.0"
serde_json = "1.0.99"
serde_with = "3.0.0"
strum = { version = "0.25.0", features = ["derive", "strum_macros"] }
strum_macros = "0.25.0"
syntect = { version = "5.0.0", features = ["default-fancy"] }
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["full"] }
tower-http = { version = "0.4.1", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
uuid = { version = "1.3.4", features = ["v1", "serde"] }
