on: [push]

name: CI

jobs:
  build:
    name: quanweb
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Archive built files
        uses: actions/upload-artifact@v3
        with:
          name: Built binaries
          path: target/release/quanweb
